# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faostgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# defines class for main gui window
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 288)
        MainWindow.setStyleSheet("QMainWindow{\n"
                                 "    background-color: rgb(123, 121, 135);\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -10, 471, 281))
        self.frame.setMaximumSize(QtCore.QSize(471, 281))
        self.frame.setStyleSheet("QFrame{\n"
                                 "    background-color: rgb(124, 128, 149);\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.leftmenutoggle = QtWidgets.QFrame(self.frame)
        self.leftmenutoggle.setGeometry(QtCore.QRect(0, 10, 91, 31))
        self.leftmenutoggle.setStyleSheet("QFrame{\n"
                                          "    background-color: rgb(91, 91, 105);\n"
                                          "}\n"
                                          "")
        self.leftmenutoggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftmenutoggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftmenutoggle.setObjectName("leftmenutoggle")
        self.label = QtWidgets.QLabel(self.leftmenutoggle)
        self.label.setGeometry(QtCore.QRect(0, 0, 91, 31))
        self.label.setStyleSheet("QLabel{    \n"
                                 "    padding: 5px 10px;\n"
                                 "    border: none;\n"
                                 "    border-radius: 10px;\n"
                                 "    background-color: rgb(91, 91, 105);\n"
                                 "    color: rgb(208, 203, 218);\n"
                                 "    font: 20pt \"Century Gothic\";\n"
                                 "}")
        self.label.setObjectName("label")
        self.sidemenu = QtWidgets.QFrame(self.frame)
        self.sidemenu.setGeometry(QtCore.QRect(0, 40, 91, 271))
        self.sidemenu.setStyleSheet("QFrame{\n"
                                    "    background-color: rgb(91, 91, 105);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    padding: 5px 10px;\n"
                                    "    border: none;\n"
                                    "    border-radius: 10px;\n"
                                    "    background-color: rgb(96, 96, 110);\n"
                                    "    color: rgb(214, 210, 226);\n"
                                    "    font: 8pt \"Century Gothic\";\n"
                                    "    cursor: \"Pointing Hand\";\n"
                                    "}\n"
                                    "QPushButton{\n"
                                    "    padding: 5px 10px;\n"
                                    "    border: none;\n"
                                    "    border-radius: 10px;\n"
                                    "    background-color: rgb(91, 91, 105);\n"
                                    "    color: rgb(214, 210, 226);\n"
                                    "    font: 8pt \"Century Gothic\";\n"
                                    "}")
        self.sidemenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidemenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidemenu.setObjectName("sidemenu")
        self.btn_admin = QtWidgets.QPushButton(self.sidemenu)
        self.btn_admin.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.btn_admin.setObjectName("btn_admin")
        self.btn_report = QtWidgets.QPushButton(self.sidemenu)
        self.btn_report.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.btn_report.setObjectName("btn_report")
        self.btn_register = QtWidgets.QPushButton(self.sidemenu)
        self.btn_register.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.btn_register.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_register.setObjectName("btn_register")
        self.btn_timetable = QtWidgets.QPushButton(self.sidemenu)
        self.btn_timetable.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.btn_timetable.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_timetable.setObjectName("btn_timetable")
        self.btn_settings = QtWidgets.QPushButton(self.sidemenu)
        self.btn_settings.setGeometry(QtCore.QRect(10, 200, 71, 21))
        self.btn_settings.setObjectName("btn_settings")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(90, 10, 381, 271))
        self.stackedWidget.setObjectName("stackedWidget")
        self.timetable = QtWidgets.QWidget()
        self.timetable.setObjectName("timetable")
        self.label_2 = QtWidgets.QLabel(self.timetable)
        self.label_2.setGeometry(QtCore.QRect(170, 130, 35, 10))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.timetable)
        self.register_2 = QtWidgets.QWidget()
        self.register_2.setObjectName("register_2")
        self.label_3 = QtWidgets.QLabel(self.register_2)
        self.label_3.setGeometry(QtCore.QRect(-6, -1, 391, 271))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.register_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(-6, -1, 381, 271))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(170, 140, 35, 10))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(180, 140, 35, 10))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # timetable button navigates to timetable widget when clicked
        self.btn_timetable.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))

        # register button navigates to register widget when clicked
        self.btn_register.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))

        # report button navigates to report widget when clicked
        self.btn_report.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))

        # settings button navigates to settings widget when clicked
        self.btn_settings.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))

        # admin button navigates to admin widget when clicked
        self.btn_admin.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FAOST"))
        self.btn_admin.setText(_translate("MainWindow", "ADMIN"))
        self.btn_report.setText(_translate("MainWindow", "REPORT"))
        self.btn_register.setText(_translate("MainWindow", "REGISTER"))
        self.btn_timetable.setText(_translate("MainWindow", "TIMETABLE"))
        self.btn_settings.setText(_translate("MainWindow", "SETTINGS"))
        self.label_2.setText(_translate("MainWindow", "timetable"))
        self.label_3.setText(_translate("MainWindow", "register"))
        self.label_4.setText(_translate("MainWindow", "report"))
        self.label_5.setText(_translate("MainWindow", "admin"))
        self.label_6.setText(_translate("MainWindow", "settings"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
