teachers = {
    10000: {name: 'English teacher 1', subject1: 'english', subject2: 'linguistics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10001: {name: 'English teacher 2', subject1: 'english', subject2: 'linguistics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10002: {name: 'English teacher 3', subject1: 'english', subject2: 'linguistics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10003: {name: 'English teacher 4', subject1: 'english', subject2: 'linguistics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10004: {name: 'English teacher 5', subject1: 'english', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10005: {name: 'English teacher 6', subject1: 'english', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10006: {name: 'English teacher 7', subject1: 'english', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10007: {name: 'English teacher 8', subject1: 'english', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10008: {name: 'English teacher 9', subject1: 'english', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10009: {name: 'English teacher 10', subject1: 'english', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10010: {name: 'Maths teacher 1', subject1: 'maths', subject2: 'further maths', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10011: {name: 'Maths teacher 2', subject1: 'maths', subject2: 'further maths', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10012: {name: 'Maths teacher 3', subject1: 'maths', subject2: 'further maths', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10013: {name: 'Maths teacher 4', subject1: 'maths', subject2: 'further maths', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10014: {name: 'Maths teacher 5', subject1: 'maths', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10015: {name: 'Maths teacher 6', subject1: 'maths', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10016: {name: 'Maths teacher 7', subject1: 'maths', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10017: {name: 'Maths teacher 8', subject1: 'maths', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10018: {name: 'Maths teacher 9', subject1: 'maths', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10019: {name: 'Maths teacher 10', subject1: 'maths', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10020: {name: 'History teacher 1', subject1: 'history', subject2: 'latin', subject3: 'classics',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10021: {name: 'History teacher 2', subject1: 'history', subject2: 'classics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10022: {name: 'History teacher 3', subject1: 'history', subject2: 'latin', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10023: {name: 'History teacher 4', subject1: 'history', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10024: {name: 'History teacher 5', subject1: 'history', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10025: {name: 'Geography teacher 1', subject1: 'geography', subject2: 'geology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10026: {name: 'Geography teacher 2', subject1: 'geography', subject2: 'geology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10027: {name: 'Geography teacher 3', subject1: 'geography', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10028: {name: 'Geography teacher 4', subject1: 'geography', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10029: {name: 'Geography teacher 5', subject1: 'geography', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10030: {name: 'Art teacher 1', subject1: 'fine art', subject2: 'photography', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10031: {name: 'Art teacher 2', subject1: 'fine art', subject2: 'photography', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10032: {name: 'Art teacher 3', subject1: 'fine art', subject2: 'photography', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10033: {name: 'Art teacher 4', subject1: 'fine art', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10034: {name: 'Art teacher 5', subject1: 'fine art', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10035: {name: 'Computer science teacher 1', subject1: 'Computer science', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10036: {name: 'Computer science teacher 2', subject1: 'Computer science', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10037: {name: 'Computer science teacher 3', subject1: 'Computer science', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10038: {name: 'Computer science teacher 4', subject1: 'Computer science', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10039: {name: 'Computer science teacher 5', subject1: 'Computer science', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10040: {name: 'Science teacher 1', subject1: 'science', subject2: 'physics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10041: {name: 'Science teacher 2', subject1: 'science', subject2: 'physics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10042: {name: 'Science teacher 3', subject1: 'science', subject2: 'physics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10043: {name: 'Science teacher 4', subject1: 'science', subject2: 'physics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10044: {name: 'Science teacher 5', subject1: 'science', subject2: 'physics', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10045: {name: 'Science teacher 6', subject1: 'science', subject2: 'chemistry', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10046: {name: 'Science teacher 7', subject1: 'science', subject2: 'chemistry', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10047: {name: 'Science teacher 8', subject1: 'science', subject2: 'chemistry', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10048: {name: 'Science teacher 9', subject1: 'science', subject2: 'chemistry', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10049: {name: 'Science teacher 10', subject1: 'science', subject2: 'chemistry', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10050: {name: 'Science teacher 11', subject1: 'science', subject2: 'biology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10051: {name: 'Science teacher 12', subject1: 'science', subject2: 'biology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10052: {name: 'Science teacher 13', subject1: 'science', subject2: 'biology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10053: {name: 'Science teacher 14', subject1: 'science', subject2: 'biology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10054: {name: 'Science teacher 15', subject1: 'science', subject2: 'biology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10055: {name: 'French teacher 1', subject1: 'french', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10056: {name: 'French teacher 2', subject1: 'french', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10057: {name: 'French teacher 3', subject1: 'french', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10058: {name: 'French teacher 4', subject1: 'french', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10059: {name: 'French teacher 5', subject1: 'french', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10060: {name: 'German teacher 1', subject1: 'German', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10061: {name: 'German teacher 2', subject1: 'German', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10062: {name: 'German teacher 3', subject1: 'German', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10063: {name: 'German teacher 4', subject1: 'German', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10064: {name: 'Construction teacher 1', subject1: 'construction', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10065: {name: 'Construction teacher 2', subject1: 'construction', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10066: {name: 'Construction teacher 3', subject1: 'construction', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10067: {name: 'Business teacher 1', subject1: 'business', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10068: {name: 'Business teacher 4', subject1: 'business', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10069: {name: 'Pe teacher 1', subject1: 'pe', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        }
            },
    10070: {name: 'Pe teacher 2', subject1: 'pe', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10071: {name: 'Pe teacher 3', subject1: 'pe', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10072: {name: 'Pe teacher 4', subject1: 'pe', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10073: {name: 'Pe teacher 5', subject1: 'pe', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10074: {name: 'Pe teacher 6', subject1: 'pe', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10075: {name: 'Pe teacher 7', subject1: 'pe', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10076: {name: 'PsyCrim teacher 1', subject1: 'psychology', subject2: 'criminology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10077: {name: 'PsyCrim teacher 2', subject1: 'psychology', subject2: 'criminology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10078: {name: 'PsyCrim teacher 3', subject1: 'psychology', subject2: 'criminology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10079: {name: 'PsyCrim teacher 1', subject1: 'psychology', subject2: 'criminology', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10080: {name: 'Dt teacher 1', subject1: 'dt', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10081: {name: 'Dt teacher 2', subject1: 'dt', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10082: {name: 'Dt teacher 3', subject1: 'dt', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    10083: {name: 'Dt teacher 2', subject1: 'dt', subject2: '', subject3: '',
            timetable: {mon: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        tues: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        wed: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        thur: {1: '', 2: '', 3: '', 4: '', 5: ''},
                        fri: {1: '', 2: '', 3: '', 4: '', 5: ''}
                        },
            },
    },
